version: '3'

services:
  mailer:
    build:
      context: .
      dockerfile: Dockerfile
    image: aquarela/mailer
    container_name: mailer
    restart: unless-stopped
    ports:
        - "4666:4666"
    networks:
        - backend-network
  proxy:
    image: nginx:mainline-alpine
    container_name: proxy
    restart: unless-stopped
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
        - mailer
    networks:
        - mailer-network
networks:
    mailer-network:
        driver: bridge
